Updated to fix jquery and bootstrap converging on newest version. Also fixed versions of supported libraries.
core-js error avoided by jumping to version "0.9.39"

Also added tsconfig.json to fix error in graphql missing AsyncIterator
  TypeScript error: ../../../node_modules/@types/graphql/subscription/subscribe.d.ts(17,4): Error TS2304: Cannot find name 'AsyncIterator'.